# Generated by Django 5.0.3 on 2024-04-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_product_size_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ssize',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
