# Generated by Django 5.0.3 on 2024-04-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='shipping_address',
        ),
    ]
