# Generated by Django 5.0.3 on 2024-04-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_shippingaddress_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
