# Generated by Django 5.0.3 on 2024-09-11 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_remove_shippingaddress_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.userprofile'),
        ),
    ]
