# Generated by Django 5.0.3 on 2024-09-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_orderpayment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='email',
        ),
    ]
